name: PyPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
    
jobs:
  build:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.8"

      - name: Build
        run: |
          python -m pip install -U pip pep517 twine
          python -m pep517.build .
      - name: Test the sdist
        run: |
          python -m venv venv-sdist
          venv-sdist/bin/python -m pip install dist/kplr*.tar.gz
          venv-sdist/bin/python -c "import kplr;print(kplr.__version__)"
      - name: Test the wheel
        run: |
          python -m venv venv-wheel
          venv-wheel/bin/python -m pip install dist/kplr*.whl
          venv-wheel/bin/python -c "import kplr;print(kplr.__version__)"
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*

  upload_pypi:
    needs: [tests, build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          # To test: repository_url: https://test.pypi.org/legacy/
